sampling_time: 0.008

wrench_topic    : "filtered_wrench_base"
vel_topic       : "current_velocity"
pos_topic       : "current_pose"

assistance_topic: "assistance"
reference_traj  : "human_target"
dwrench_topic   : "delta_force"

robot_has_human_reference: true

max_fl: 0.007
